# Generated by Django 4.1.3 on 2022-11-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=10)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('lastdonatedate', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
